config/routes.rb
Rails.application.routes.draw do
  resources :mentors
  root "mentors#index"
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
	validates_presence_of :name, :email, :occupation, :company
	validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_action :set_mentor, only: [:show, :edit, :update, :destroy]

  # GET /mentors
  # GET /mentors.json
  def index
    @search = Mentor.paginate(:page => params[:page], :per_page => 20).search(params[:q])
    @mentors = @search.result
    #@mentors = @q.result.includes(:name)
  end

  # GET /mentors/1
  # GET /mentors/1.json
  def show
  end

  # GET /mentors/new
  def new
    @mentor = Mentor.new
  end

  # GET /mentors/1/edit
  def edit
  end

  # POST /mentors
  # POST /mentors.json
  def create
    @mentor = Mentor.new(mentor_params)

    respond_to do |format|
      if @mentor.save
        format.html { redirect_to @mentor, notice: 'Mentor was successfully created.' }
        format.json { render :show, status: :created, location: @mentor }
      else
        format.html { render :new }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mentors/1
  # PATCH/PUT /mentors/1.json
  def update
    respond_to do |format|
      if @mentor.update(mentor_params)
        format.html { redirect_to @mentor, notice: 'Mentor was successfully updated.' }
        format.json { render :show, status: :ok, location: @mentor }
      else
        format.html { render :edit }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentors/1
  # DELETE /mentors/1.json
  def destroy
    @mentor.destroy
    respond_to do |format|
      format.html { redirect_to mentors_url, notice: 'Mentor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mentor
      @mentor = Mentor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mentor_params
      params.require(:mentor).permit(:name, :email, :occupation, :company)
    end

    def filtering_params
      params.slice(:name, :occupation, :company)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dowhatnow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mentors/_form.html.erb
<%= form_for(@mentor) do |f| %>
  <% if @mentor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mentor.errors.count, "error") %> prohibited this mentor from being saved:</h2>

      <ul>
      <% @mentor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br>
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mentors/edit.html.erb
<h1>Editing Mentor</h1>

<%= render 'form' %>

<%= link_to 'Show', @mentor %> |
<%= link_to 'Back', mentors_path %>

app/views/mentors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mentors</h1>

<table class="nil">
<%= search_form_for @search do |f| %>
  <tr class="nil">
  <td class="nil"><%= f.label :name_cont, "Name contains: " %></td>
  <td class="nil"><%= f.search_field :name_cont %></td>
  </tr>
  <tr class="nil">
  <td class="nil"><%= f.label :company_cont, "Company contains: " %></td>
  <td class="nil"><%= f.search_field :company_cont %></td>
  </tr>
  <tr class="nil">
  <td class="nil"><%= f.label :occupation_cont, "Occupation contains: " %></td>
  <td class="nil"><%= f.search_field :occupation_cont %></td>
  <tr class="nil">
    <td class="nil"><%= f.submit %></td>
  </tr>
<% end %>
</table>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Occupation</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mentors.each do |mentor| %>
      <tr>
        <td><%= mentor.name %></td>
        <td><%= mentor.email %></td>
        <td><%= mentor.occupation %></td>
        <td><%= mentor.company %></td>
        <td><%= link_to 'Show', mentor %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @mentors %>

<br>

<%= link_to 'New Mentor', new_mentor_path %>

app/views/mentors/new.html.erb
<h1>New Mentor</h1>

<%= render 'form' %>

<%= link_to 'Back', mentors_path %>

app/views/mentors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mentor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @mentor.email %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @mentor.occupation %>
</p>

<p>
  <strong>Company:</strong>
  <%= @mentor.company %>
</p>

<%= link_to 'Edit', edit_mentor_path(@mentor) %> |
<%= link_to 'Back', mentors_path %>